"""initial schema

Revision ID: 605eea56b1e3
Revises: 
Create Date: 2026-09-15 17:04:37.400869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605eea56b1e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_attempts', sa.Integer(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_recovery_codes_hash', sa.Text(), nullable=True),
    sa.Column('device_fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_device_fingerprint_hash'), 'auth_users', ['device_fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_phone'), 'auth_users', ['phone'], unique=True)
    op.create_index(op.f('ix_auth_users_verification_status'), 'auth_users', ['verification_status'], unique=False)
    op.create_table('auth_otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_otp_codes_email'), 'auth_otp_codes', ['email'], unique=False)
    op.create_index(op.f('ix_auth_otp_codes_expires_at'), 'auth_otp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_otp_codes_user_id'), 'auth_otp_codes', ['user_id'], unique=False)
    op.create_index('ix_otp_email_purpose', 'auth_otp_codes', ['email', 'purpose'], unique=False)
    op.create_table('auth_passkey_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.String(length=512), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('aaguid', sa.String(length=64), nullable=True),
    sa.Column('transports', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_passkey_credentials_credential_id'), 'auth_passkey_credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_auth_passkey_credentials_user_id'), 'auth_passkey_credentials', ['user_id'], unique=False)
    op.create_table('auth_refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_refresh_tokens_token_hash'), 'auth_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_refresh_tokens_user_id'), 'auth_refresh_tokens', ['user_id'], unique=False)
    op.create_table('auth_verification_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number_hash', sa.String(length=64), nullable=False),
    sa.Column('selfie_path', sa.Text(), nullable=False),
    sa.Column('document_front_path', sa.Text(), nullable=False),
    sa.Column('document_back_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_verification_requests_document_number_hash'), 'auth_verification_requests', ['document_number_hash'], unique=False)
    op.create_index(op.f('ix_auth_verification_requests_status'), 'auth_verification_requests', ['status'], unique=False)
    op.create_index(op.f('ix_auth_verification_requests_user_id'), 'auth_verification_requests', ['user_id'], unique=False)
    op.create_index('ix_verification_document_hash_approved', 'auth_verification_requests', ['document_number_hash'], unique=True, postgresql_where=sa.text("status = 'approved'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verification_document_hash_approved', table_name='auth_verification_requests', postgresql_where=sa.text("status = 'approved'"))
    op.drop_index(op.f('ix_auth_verification_requests_user_id'), table_name='auth_verification_requests')
    op.drop_index(op.f('ix_auth_verification_requests_status'), table_name='auth_verification_requests')
    op.drop_index(op.f('ix_auth_verification_requests_document_number_hash'), table_name='auth_verification_requests')
    op.drop_table('auth_verification_requests')
    op.drop_index(op.f('ix_auth_refresh_tokens_user_id'), table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_token_hash'), table_name='auth_refresh_tokens')
    op.drop_table('auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_passkey_credentials_user_id'), table_name='auth_passkey_credentials')
    op.drop_index(op.f('ix_auth_passkey_credentials_credential_id'), table_name='auth_passkey_credentials')
    op.drop_table('auth_passkey_credentials')
    op.drop_index('ix_otp_email_purpose', table_name='auth_otp_codes')
    op.drop_index(op.f('ix_auth_otp_codes_user_id'), table_name='auth_otp_codes')
    op.drop_index(op.f('ix_auth_otp_codes_expires_at'), table_name='auth_otp_codes')
    op.drop_index(op.f('ix_auth_otp_codes_email'), table_name='auth_otp_codes')
    op.drop_table('auth_otp_codes')
    op.drop_index(op.f('ix_auth_users_verification_status'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_phone'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_device_fingerprint_hash'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
