"""add webauthn challenges table

Revision ID: f5b236f5e39a
Revises: 15c92bd6ea7e
Create Date: 2026-09-18 12:48:30.027474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b236f5e39a'
down_revision: Union[str, Sequence[str], None] = '15c92bd6ea7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_webauthn_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('challenge', sa.String(length=255), nullable=False),
    sa.Column('challenge_type', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_webauthn_challenges_challenge'), 'auth_webauthn_challenges', ['challenge'], unique=False)
    op.create_index(op.f('ix_auth_webauthn_challenges_email'), 'auth_webauthn_challenges', ['email'], unique=False)
    op.create_index(op.f('ix_auth_webauthn_challenges_expires_at'), 'auth_webauthn_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_webauthn_challenges_user_id'), 'auth_webauthn_challenges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_webauthn_challenges_user_id'), table_name='auth_webauthn_challenges')
    op.drop_index(op.f('ix_auth_webauthn_challenges_expires_at'), table_name='auth_webauthn_challenges')
    op.drop_index(op.f('ix_auth_webauthn_challenges_email'), table_name='auth_webauthn_challenges')
    op.drop_index(op.f('ix_auth_webauthn_challenges_challenge'), table_name='auth_webauthn_challenges')
    op.drop_table('auth_webauthn_challenges')
    # ### end Alembic commands ###
